Repository javascript-spec/ubiquitous-happiness, pull requests merged in 2022-10, with the labels that each got.

#1 added heapsort
  Sorting/HeapSort.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#2 implemented mergesort in py
  Sorting/MergeSort.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#3 [added]: Selection Sort Python File in Sorting Folder
  Sorting/BubbleSort.py
  Sorting/SelectionSort.py
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#6 Added: Radix Sort
  Sorting/InsertionSort.py
  Sorting/RadixSort.py
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest2022

#7 Update BinarySearch.js
  Algo/JS/BinarySearch.js
Labels: hacktoberfest-accepted, hacktoberfest
